Small quick fixes
digitalcredentials/dcc-website pull request #92
Opened 2024-05-08 11:46 UTC by LauraHilliger

Adding a link to github to the footer, updating the copyright year to 2024, fixing a broken a link and updating the mission on the start page to match the one you've been using

2024-06-04 02:42 UTC, kayaelle requested changes
Heya - let's leave Philipp, Brandon, & Kayode up there for now. Thanks!

2024-06-04 12:18 UTC, LauraHilliger commented
@kayaelle I reverted the commit with that change, should be good now?

2024-06-10 21:28 UTC, kayaelle approved these changes

2024-06-10 21:28 UTC, kayaelle commented
Thanks, @LauraHilliger !

2024-06-10 21:28 UTC, merged